version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-progress

  build:
    commands:
      - echo "Building frontend..."
      - npm run build
      - if [ -d "out" ]; then mv out dist; elif [ -d "build" ]; then mv build dist; fi

artifacts:
  files:
    - "dist/**/*"
  name: FrontendBuildOutput

cache:
  paths:
    - "~/.npm/**/*"

