version: 0.2

env:
  variables:
    NPM_CONFIG_PRODUCTION: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-progress

  build:
    commands:
      - echo "Running unit tests..."
      - npm run test || true
      - mkdir -p coverage test-results
      - touch coverage/.placeholder test-results/.placeholder

artifacts:
  files:
    - "coverage/**/*"
    - "test-results/**/*"
  name: UnitTestsOutput

cache:
  paths:
    - "~/.npm/**/*"

